### PR TITLE
Online instrumentation mode

### PR DESCRIPTION
**Pull request by andre15silva**
I'm working on this PR, which features a new mode for getting the covered test results through online instrumentation, instead of through offline instrumentation as it is the case of all modes right now.

The advantages are:
- No inconsistencies between classloaders. (see https://github.com/SpoonLabs/flacoco/issues/85). This means that we just need to set the classpath with all binaries (dependencies, tests, source) in it and that's it.
- Support for cases where no access to the specific binary directories is available (see https://github.com/SpoonLabs/flacoco), only the classpath and test cases.
- With the options `includes` and `excludes`, we can optimize the analysis/instrumentation without any PR to `jacoco`. Related to https://github.com/STAMP-project/test-runner/issues/111
- We can finally cover tests if we want to (see https://github.com/STAMP-project/test-runner/issues/96), it is just a matter of setting the test classes to be included.

The PR's main work is finished. Tomorrow I'll finish adding tests and testing the remaining integration with `flacoco` and other tools. 

Early feedback is appreciated though, specifically if you want to merge some `test-runner` modes.

### CODE REVIEW

**Comment by andre15silva** [comment]
`coveralls` is failing because it doesn't find the source files of the jacoco agent.

The `coveralls-maven-plugin` does not have the option to ignore these errors (https://github.com/trautonen/coveralls-maven-plugin/issues/113).

**Comment by andre15silva** [comment]
@danglotb I have cherry-picked the commits that replace the coverage platform to https://github.com/STAMP-project/test-runner/pull/118.

After that is merged, I'll rebase here and this will be ready too.

**Comment by andre15silva** [comment]
Thank you @danglotb !

This one is ready now too.

**Comment by andre15silva** [comment]
@danglotb do you have any timeline of when you will be able to review this PR?

This PR is blocking https://github.com/SpoonLabs/flacoco/pull/86, https://github.com/SpoonLabs/astor/pull/323 and https://github.com/SpoonLabs/nopol/pull/220 and I'd like to finish it them by the end of this week (when I finish my internship) :sweat_smile:

**Review by danglotb — APPROVED** [review]

**Comment by andre15silva** [comment]
Thanks!

**Pull request merged**
