### PR TITLE
CoveredTestResultPerTestMethod API

### PR DESCRIPTION
**Pull request by andre15silva**
This PR introduces a new API in `test-runner`'s `EntryPoint`.

It's purpose is to return a `CoveredTestResultPerTestMethod` object, which contains the information relative to the coverage per test method, as well as the test execution results.

### CODE REVIEW

**Comment by andre15silva** [comment]
If you want to review the current state of the PR, the content shouldn't change much.

I'm working on a few more test cases to cover everything new.

**Comment by monperrus** [comment]
Cool, thanks @andre15silva. @danglotb would you be available for a code review?

**Comment by andre15silva** [comment]
PR ready for review.

I have a pending issue with `test-runner`'s usage in https://github.com/SpoonLabs/flacoco/pull/35#issuecomment-867634527, but since this API works in the `test-runner`'s test suite, I'm not sure what is causing it.

**Review by danglotb — APPROVED** [review]
Overall the changes look good to me.

However, I have to open question for the future of `test-runner :
1. I'm asking myself if we could reduce the code redundancies by encapsulating a `TestResultImpl` in the `CoveredTestResultPerTestMethodImpl` to avoid a bit the redundancies.
2. Should we keep `CoveragePerTestMethod` and `Coverage` since we have now a richer object for the same "price", _i.e._ `Coverage` + `TestResult`?

I'll merge the changes ASAP the CI is ok.

Thank you for your contributions! Good job

**Comment by danglotb** [comment]
You increased the coverage! https://coveralls.io/jobs/82527638 Thank you

**Pull request merged**
