### PR TITLE
Bump jacoco to 0.8.8

### LINKED ISSUE #138: Bump JaCoCo to 0.8.8
See https://github.com/SpoonLabs/flacoco/issues/171

### PR DESCRIPTION
**Pull request by andre15silva**
Closes #138

### CODE REVIEW

**Comment by monperrus** [comment]
cool!

ping @danglotb

**Comment by danglotb** [comment]
Thank you @andre15silva ! :confetti_ball:

**Comment by danglotb** [comment]
The deployment after this commit is failing, therefore `test-runner-4.7` is not yet available.

It seems that the curl command that gets the previous version is failing. 

The URL `https://www.monperrus.net/martin/last-version-maven.py?groupId=eu.stamp-project&artifactId=test-runner` is returning an internal server error 500.

ping @monperrus

Thank you :smile:

**Comment by monperrus** [comment]
fixed and released!

**Pull request merged**
