### PR TITLE
Fix null exception in anyTestMethodNamesMatch predicate

### PR DESCRIPTION
**Pull request by andre15silva**
Sometimes, the `Description` object given to the `anyTestMethodNamesMatch` predicate does not represent a method.

In those cases, the `ListenerUtils.getMethodName` function returns `null`, leading to a `NullPointerException` when we try to match said `null` object in a regex Matcher in https://github.com/STAMP-project/test-runner/blob/a2fc403dd51d6b94e967a1428afc1e06de718c55/src/main/java/eu/stamp_project/testrunner/runner/MethodFilter.java#L46-L54

This PR fixes that issue by introducing a null check in said predicate.

### CODE REVIEW

**Comment by andre15silva** [comment]
Hi @danglotb :)

Would you be able to review this PR?
It is linked with https://github.com/SpoonLabs/flacoco/issues/153#issuecomment-1437407100

Merci!

**Comment by danglotb** [comment]
LGTM

**Comment by andre15silva** [comment]
Thanks :)

**Comment by monperrus** [comment]
cool!

**Pull request merged**
