### PR TITLE
FEAT: Add test framework package from dspot

### PR DESCRIPTION
**Pull request by danglotb**
Some part of this code is completly dedicated to DSpot. I guess that it would be great to better slice it and / or avoid any commented code.
However, in order to let @martinezmatias move forward, I suggest moving the code like this (if this works for what you have to do). 

And then, I'll refactor (huge technical debts here, but I'll be on holiday some day...) the code.

For the DSpot side, there a bunch of refactoring / wrapping of the code. I'll have a look at this.

WDYT @monperrus @martinezmatias ?

### CODE REVIEW

**Comment by danglotb** [comment]
Tests are on their way BTW; Who I would be if I do not provide any test? :trollface:

**Comment by monperrus** [comment]
Waoow, really cool.

Let's test and merge. Yeah :)

**Comment by monperrus** [comment]
@danglotb ready to merge?

**Comment by danglotb** [comment]
I'm sorry I don't have the time right now to test this. I guess that we can merge it as it is if it is blocking for @martinezmatias.

I keep track of this in order to test and pursue the refactoring of **DSpot** when I have the chance.

**Comment by monperrus** [comment]
No problem, I propose to merge this and rebase #80 afterwards. @martinezmatias WDYT?

**Comment by martinezmatias** [comment]
Let's do it :)

**Comment by monperrus** [comment]
Merged thanks Benjamin. Matias, you can proceed with rebase your PR.

**Comment by martinezmatias** [comment]
Hi @monperrus 
I think that Github provides [an option for automatically rebase](https://github.blog/2016-09-26-rebase-and-merge-pull-requests/) the put request during the merge of the PR:
image

**Pull request merged**
